import { defineTool } from '@deepseek-ai/dsh-tools'

const templates = {
  node: ['node_modules/', '.npm/', '.yarn/', '.pnp.*', 'npm-debug.log*', 'yarn-debug.log*', 'pnpm-debug.log*', 'dist/', 'build/'],
  python: ['__pycache__/', '*.py[cod]', '*$py.class', '.venv/', 'venv/', 'ENV/', 'build/', 'dist/', '*.egg-info/', '.pytest_cache/', '.mypy_cache/', '.ruff_cache/', '.coverage*'],
  dotnet: ['bin/', 'obj/', '*.user', '*.suo', '.vs/', 'TestResults/'],
  java: ['*.class', '*.log', 'target/', 'build/', '.gradle/', 'out/'],
  rust: ['/target/'],
  go: ['*.exe', '*.test', '*.out', 'coverage.out'],
  vscode: ['.vscode/*', '!.vscode/settings.json', '!.vscode/tasks.json', '!.vscode/launch.json', '!.vscode/extensions.json'],
  jetbrains: ['.idea/', '*.iml'],
  macos: ['.DS_Store', '.AppleDouble', '.LSOverride', '._*'],
  windows: ['Thumbs.db', 'Thumbs.db:encryptable', 'Desktop.ini', '$RECYCLE.BIN/'],
  linux: ['*~', '.directory'],
  terraform: ['.terraform/', '*.tfstate', '*.tfstate.*', 'crash.log', 'crash.*.log', 'override.tf', 'override.tf.json', '*_override.tf', '*_override.tf.json'],
  secrets: ['.env', '.env.*', '!.env.example', '!.env.sample', '*.pem', '*.key'],
}

const supported = Object.keys(templates)

function build({ stacks }) {
  if (!Array.isArray(stacks) || stacks.length === 0) throw new Error('Choose at least one stack or tool.')
  if (stacks.length > supported.length) throw new Error(`Choose no more than ${supported.length} entries.`)

  const selected = [...new Set(stacks.map((item) => String(item).trim().toLowerCase()))]
  const unknown = selected.filter((item) => !Object.hasOwn(templates, item))
  if (unknown.length) throw new Error(`Unknown entries: ${unknown.join(', ')}. Supported: ${supported.join(', ')}.`)

  const lines = new Set([
    '# Generated by GhosTnever DSH Toolkit: gitignore-builder',
    '# Review these patterns for your project before committing.',
    '',
  ])
  for (const stack of selected) {
    lines.add(`# ${stack}`)
    for (const pattern of templates[stack]) lines.add(pattern)
    lines.add('')
  }

  const gitignore = [...lines].join('\n').trimEnd() + '\n'
  return { selectedStacks: selected, patternCount: [...lines].filter((line) => line && !line.startsWith('#')).length, gitignore }
}

const outputSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    selectedStacks: { type: 'array', items: { type: 'string' } },
    patternCount: { type: 'number' },
    gitignore: { type: 'string' },
  },
}

export const name = 'dsh-ghostnever-gitignore-builder'
export const inject = ['tools']

export function apply(ctx) {
  ctx.tools.register(defineTool({
    name: 'dsh_ghostnever_gitignore_builder',
    description: 'Generate a deduplicated .gitignore template from selected languages, tools, and operating systems. It does not read or modify repository files.',
    parameters: {
      stacks: {
        type: 'array',
        required: true,
        items: { type: 'string' },
        description: `One or more entries: ${supported.join(', ')}.`,
      },
    },
    output: {
      schema: outputSchema,
      render: (_args, value) => [{ type: 'text', text: JSON.stringify(value, null, 2) }],
    },
    async execute(args) {
      return build(args)
    },
  }))
}
